RejestrOsobZaginionych/Controllers/OsobyZaginioneController.cs
using RejestrOsobZaginionych.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace RejestrOsobZaginionych.Controllers
{
    public class OsobyZaginioneController : Controller
    {
        public OsobaZaginionaDbContext db = new OsobaZaginionaDbContext();
        public UzytkownikDbContext db2 = new UzytkownikDbContext();

        // GET: OsobyZaginione
        [LoginFilter]
        public ActionResult Index(int err = 1, int utworzono = 0)
        {
            if (Session["zalogowany"].ToString() == "1")
            {
                return RedirectToAction("List");
            }

            ViewBag.Utworzono = utworzono;            
            ViewBag.Error = err;
            return View();        
        }

        [LoginFilter]
        public ActionResult List(int plec = 0)
        {
            if (Session["zalogowany"].ToString() != "1")
            {
                return RedirectToAction("Index");
            }
            if (plec != 1 && plec != 2 && plec != 0)
            {
                plec = 0; 
            }

            ViewBag.Plec = plec;
            ViewBag.Sciezka = Path.Combine(Server.MapPath("~/zdjecia"));
            ViewBag.Admin = Session["admin"].ToString();
            return View(db.OsobyZaginione.ToList());
    }
        
        // GET: OsobyZaginione/Create
        [LoginFilter]
        public ActionResult Create()
        {
            if (Session["zalogowany"].ToString() != "1")
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        // POST: OsobyZaginione/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Imie,Nazwisko,Opis,Plec")] OsobaZaginiona osobaZaginiona, HttpPostedFileBase plik)
        {
            if (ModelState.IsValid)
            {
                osobaZaginiona.Zdjecie = "";
                if (plik != null)
                {
                    string sciezka = Path.Combine(Server.MapPath("~/zdjecia"), Path.GetFileName(plik.FileName));
                    plik.SaveAs(sciezka);
                    osobaZaginiona.Zdjecie = plik.FileName;
                }
                db.OsobyZaginione.Add(osobaZaginiona);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(osobaZaginiona);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Logowanie([Bind(Include = "Email,Haslo")] Uzytkownik uzytkownik)
        {
            int error = 1;
            if (ModelState.IsValid)
            {
                bool prawidlowyEmail = db2.Uzytkownicy.Any(x => x.Email == uzytkownik.Email);
                if (prawidlowyEmail)
                {
                    if (uzytkownik.Haslo != null)
                    {
                        var uzytkownikzbazy = db2.Uzytkownicy.Where(x => x.Email == uzytkownik.Email)
                            .Single();

                        bool prawidloweHaslo = Crypto.VerifyHashedPassword(uzytkownikzbazy.Haslo, uzytkownik.Haslo);

                        if (prawidloweHaslo && uzytkownikzbazy.Aktywny)
                        {
                            Session["UzytkownikID"] = uzytkownikzbazy.ID;
                        }
                        else
                        {
                            error = -1;
                        }
                    } else
                    {
                        error = -1;
                    }

                }
                else
                {
                    error = 0;
                }
            }
            return RedirectToAction("Index", new { err = error});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Rejestracja([Bind(Include = "Email,Haslo")] Uzytkownik uzytkownik)
        {
            if (ModelState.IsValid && uzytkownik.Email != null && uzytkownik.Haslo != null)
            {
                uzytkownik.Admin = false;
                uzytkownik.Aktywny = false;
                uzytkownik.Haslo = Crypto.HashPassword(uzytkownik.Haslo);
                db2.Uzytkownicy.Add(uzytkownik);
                db2.SaveChanges();
                return RedirectToAction("Index", new { utworzono = 1 });
            } 
            else
            {
                return RedirectToAction("Index", new { utworzono = -1 });
            }

            return View(uzytkownik);
        }

        public ActionResult Wyloguj()
        {
            Session.Remove("UzytkownikID");
            Session.Remove("zalogowany");
            Session.Remove("aktywny");
            Session.Remove("admin");
            Session.Remove("test");
            return RedirectToAction("Index");
        }
    }
}

RejestrOsobZaginionych/Views/OsobyZaginione/Create.cshtml
@model RejestrOsobZaginionych.Models.OsobaZaginiona

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>

	<link rel="stylesheet" href="/Content/bootstrap.min.css">

	<script src="/Scripts/jquery-3.4.1.min.js"></script>
	<script src="/Script/bootstrap.js"></script>
</head>
<body class="container">
    @using (Html.BeginForm("Create", "OsobyZaginione", FormMethod.Post, new{ enctype = "multipart/form-data" })) 
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>OsobaZaginiona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zdjecie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                <input type="file" name="plik">
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Plec, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="Plec" id="kobieta" value="1" checked>
                    <label class="form-check-label" for="kobieta">
                        Kobieta
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="Plec" id="mezczyzna" value="2">
                    <label class="form-check-label" for="mezczyzna">
                        Mężczyzna
                    </label>
                </div>
                @Html.ValidationMessageFor(model => model.Plec, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Stworz" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Wróć do listy", "Index")
    </div>
</body>
</html>

RejestrOsobZaginionych/Views/OsobyZaginione/Index.cshtml
@model RejestrOsobZaginionych.Models.Uzytkownik

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
	<link rel="stylesheet" href="/Content/bootstrap.min.css">
</head>
<body class="container">
    @if (ViewBag.Utworzono == 1)
    {
		<div class="alert alert-success">
			<p>Konto zostało utworzone! Poczekaj na akceptację przez administratora.</p>
		</div>
    }
	else if (ViewBag.Utworzono == -1) 
	{
		<div class="alert alert-warning">
			<p>Aby się zarejestrować wypełnij wszystkie pola.</p>
		</div>
	}

    @if (ViewBag.Error == 0)
    {
		<div class="alert alert-danger">
			<p>Takie konto nie istnieje. Najpierw się zarejestruj.</p>
		</div>
    }
    else if (ViewBag.Error == -1)
    {
		<div class="alert alert-danger">
			<p>Nieprawidłowe hasło lub konto nieaktywne.</p>
		</div>

    }

    @using (Html.BeginForm("Logowanie", "OsobyZaginione"))
    {


        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Logowanie</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Haslo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.Haslo, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                    @Html.ValidationMessageFor(model => model.Haslo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Zaloguj" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    @using (Html.BeginForm("Rejestracja", "OsobyZaginione"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Rejestracja</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Haslo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.Haslo, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                    @Html.ValidationMessageFor(model => model.Haslo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Zarejestruj" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <script src="/Scripts/jquery-3.4.1.min.js"></script>
	<script src="/Script/bootstrap.js"></script>
</body>
</html>

RejestrOsobZaginionych/Views/OsobyZaginione/List.cshtml
@model IEnumerable<RejestrOsobZaginionych.Models.OsobaZaginiona>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>index</title>
	<link rel="stylesheet" href="/Content/bootstrap.min.css">

</head>
<body class="container">
    <p>
        <a href="/OsobyZaginione/List">Lista zaginionych</a> |
        @if (ViewBag.Admin == "1")
        {
            <span><a href="/Admin">Zarządzanie użytkownikami</a> |</span>
        }
        <a href="/OsobyZaginione/Wyloguj">Wyloguj</a>
    </p>
    <p>
        Filtrowanie:
        <a href="/OsobyZaginione/List">Wszyscy</a>
        <a href="/OsobyZaginione/List/?plec=1">Kobiety</a>
        <a href="/OsobyZaginione/List/?plec=2">Mężczyźni</a>
    </p>
    @if (ViewBag.Plec == 1)
    {
        <p>Filtrowanie: [Płeć: Kobieta]</p>
    }
    else if (ViewBag.Plec == 2)
    {
        <p>Filtrowanie: [Płeć: Mężczyzna]</p>
    }


    <p>
        @Html.ActionLink("Dodaj", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Imie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nazwisko)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zdjecie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Plec)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            if (ViewBag.Plec == item.Plec || ViewBag.Plec == 0)
            {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Imie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nazwisko)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Opis)
        </td>
        @if (item.Zdjecie == "")
        {
            <td>Brak</td>
        }
        else
        {
            <td class="text-center">
                <img src="@Url.Content("~/zdjecia/" + item.Zdjecie)" style="max-width: 200px;"/>
            </td>
        }
        @if (item.Plec == 1)
        {
            <td>Kobieta</td>
        }
        else if (item.Plec == 2)
        {
            <td>Mężczyzna</td>
        }
    </tr>
            }
        }

    </table>

	<script src="/Scripts/jquery-3.4.1.min.js"></script>
	<script src="/Script/bootstrap.js"></script>
</body>
</html>